### ISSUE TITLE
Failed to execute goal com.github.github:downloads-maven-plugin:0.1 :upload

### ISSUE THREAD

**Issue by rajeshkp** [kevinsawicki/github-maven-example#1]
I am using Maven 3.0.3 and my github credentials seems to be valid. Why does it fail to upload?

[ERROR] Failed to execute goal com.github.github:downloads-maven-plugin:0.1
:upload (default) on project github-maven-example: Deleting existing downlo
ad github-maven-example-0.1-SNAPSHOT.jar failed: Not Found (404) -> [Help 1
]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
 switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, pleas
e read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecu
tionException

**Comment by kevinsawicki** [comment]
Hi, can you run with -X and include the output?

Are you using your GitHub password or an OAuth token?

**Comment by kevinsawicki** [comment]
Also, did you update the `<url>` and `<scm>` sections of the pom.xml file to be your fork?

**Comment by rajeshkp** [comment]
My repository URL was incorrect, seems to be working fine.
